# -*- coding: utf-8 -*-
"""TFIDF_Pinterest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkjnPeIZbTe82K3Fm-UTVbYgZVUULaP8
"""

import pandas as pd
import numpy as np
import nltk
from TFIDF import TFIDF
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# Load data Pinterest
df = pd.read_csv("pinterest_sentiment.csv")
df = df.dropna(subset=['review'])

X_raw = df['review'].values
y = df['sentiment']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

tfidf_custom = TFIDF(X_raw)

# 1. Jalankan preprocessing teks
tfidf_custom.preprocessing_text()

# 2. Saring ulasan yang menjadi kosong setelah preprocessing
# Kita harus menyelaraskan X dan y agar baris yang kosong dihapus dari keduanya
non_empty_mask = np.array([len(doc.strip()) > 0 for doc in tfidf_custom.norm_corpus])

# Update corpus di dalam objek dan juga label y_encoded
tfidf_custom.norm_corpus = tfidf_custom.norm_corpus[non_empty_mask]
y_filtered = y_encoded[non_empty_mask]

# 3. Hitung matriks TF pada data yang sudah disaring
tf_matrix = tfidf_custom.tf()

# 4. Hitung DF dan IDF
df_values = tfidf_custom.df(tf_matrix)
idf_vector, idf_matrix = tfidf_custom.idf(df_values)

# 5. Hitung TF-IDF (sekarang tidak akan ada pembagian dengan nol)
X_tfidf = tfidf_custom.tfidf(tf_matrix, idf_vector)

print(f"Data asli: {len(X_raw)}")
print(f"Data setelah membuang ulasan kosong: {len(X_tfidf)}")

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y_filtered, test_size=0.2, random_state=42)

models = {
    "Linear SVC": LinearSVC(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(f"--- {name} Performance ---")
    print(f"Accuracy: {accuracy_score(y_test, predictions):.4f}")
    print(classification_report(y_test, predictions, target_names=le.classes_))
    print("\n")